### ISSUE TITLE
Check yarn-lock or package-lock

### ISSUE THREAD

**Issue by davesnx** [d4rkr00t/whybundled#2]
Hey @d4rkr00t 

Thanks for the CLI, It solves a current issue that I had in the past. My problem was more... which dependant have this dependency. I ended up with a bash script that was searching for the name with [jq](https://stedolan.github.io/jq/) and get the previous keys.

Do you think that this module would make sense to not work with `webpack` at all? I didn't have time to check out the source itself and might be a big change, but it's reasonable to ask.

Feel free to reject if there's not a viable solution!

Thanks!

**Comment by simonkberg** [comment]
You should be able to use [`yarn why`](https://yarnpkg.com/en/docs/cli/why) for that.

![screenshot from 2018-02-27 21-36-35](https://user-images.githubusercontent.com/173085/36753543-bb7a5c0c-1c06-11e8-831f-c70568cd93bb.png)

**Comment by d4rkr00t** [comment]
Unfortunately this module can't work without webpack, because it uses stats.json from webpack to build a report. That allows for things like:
* Exact reasons e.g. file name that imported particular module
* What files were included from a module
* How many times some module has been imported
* etc...

And yeah, I have the same issue with finding who depends on a module :) And not everybody is using yarn so, even though `yarn why` is awesome, npm doesn't have anything like that :( 

As for this tool – it has a little bit different purpose...

**Comment by davesnx** [comment]
Thanks @simonkberg and @d4rkr00t it make sense.
